#!/bin/bash
# Weekly Report Generator
# 生成每周智能体工作总结

set -e

WORKSPACE="/home/admin/.openclaw/workspace"
TASKS_FILE="$WORKSPACE/.clawdbot/active-tasks.json"
REPORTS_DIR="$WORKSPACE/reports"

mkdir -p "$REPORTS_DIR"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [REPORT] $1"
}

# 计算统计数据
total_tasks=$(jq '.tasks | length' "$TASKS_FILE")
completed_tasks=$(jq '[.tasks[] | select(.status == "done")] | length' "$TASKS_FILE")
running_tasks=$(jq '[.tasks[] | select(.status == "running")] | length' "$TASKS_FILE")

# 按智能体类型统计
codex_count=$(jq '[.tasks[] | select(.agent == "codex")] | length' "$TASKS_FILE")
claude_count=$(jq '[.tasks[] | select(.agent == "claude")] | length' "$TASKS_FILE")
gemini_count=$(jq '[.tasks[] | select(.agent == "gemini")] | length' "$TASKS_FILE")

# 生成报告
report_date=$(date '+%Y-%m-%d')
cat > "$REPORTS_DIR/weekly-$report_date.md" << EOF
# Weekly Agent Report - $report_date

## Summary

| Metric | Value |
|--------|-------|
| Total Tasks | $total_tasks |
| Completed | $completed_tasks |
| Running | $running_tasks |
| Success Rate | $(echo "scale=1; $completed_tasks * 100 / $total_tasks" | bc)% |

## Agent Usage

| Agent | Tasks | Percentage |
|-------|-------|------------|
| Codex | $codex_count | $(echo "scale=1; $codex_count * 100 / $total_tasks" | bc)% |
| Claude Code | $claude_count | $(echo "scale=1; $claude_count * 100 / $total_tasks" | bc)% |
| Gemini | $gemini_count | $(echo "scale=1; $gemini_count * 100 / $total_tasks" | bc)% |

## Completed Tasks This Week

$(jq -r '.tasks[] | select(.status == "done") | "- **\(.id)**: \(.description) (\(.agent))"' "$TASKS_FILE")

## Running Tasks

$(jq -r '.tasks[] | select(.status == "running") | "- **\(.id)**: \(.description) (\(.agent)) - Started: \(.startedAt | todate)"' "$TASKS_FILE")

---
Generated by Zoe Orchestrator
EOF

log "Weekly report generated: $REPORTS_DIR/weekly-$report_date.md"

# 可选：发送到 Telegram
if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
    "$WORKSPACE/scripts/notify-telegram.sh" daily-summary "$completed_tasks" "0" "0"
fi
